

<div class="container">
    <header class="jumbotron masthead">
            <h1>TwiDel</h1>
            <p>Сервис для делегирования управления своим twitter-аккаунтом</p>
        <p class="download-info">Чтобы начать пользоваться сервисом вам необходомо <a class="btn btn-primary btn-large" href="./redirect.php">войти, используя twitter</a></p>

    </header>

    <hr class="soften">
    <div class="marketing">
        <h1>Возможности:</h1>
        <p class="marketing-byline">
            Пока это все что есть, но мы работаем над расширением функционала
        </p>
        <div class="row">
			<div class="span6">
                <h2>Написание твитов</h2>
                <p>Вы можете писать твиты от любого аккаунта, предоставившего вам доступ</p>
            </div>
            <div class="span6">
                <h2>Выдача прав</h2>
                <p>Просто введите имя пользователя чтобы дать ему доступ.</p>
            </div>
        </div>
		<div class="row">
            <div class="span6">
                <h2>Бесплатно</h2>
                <p>Сервис абсолютно бесплатен и не имеет ограничений на количество делегаций!</p>
            </div>
            <div class="span6">
                <h2>Безопасно</h2>
                <p>Никто не узнает вашего пароля - чтобы отключить работу сервиса просто удалите приложение TwiDel из приложений twitter</p>
            </div>
        </div>
    </div>
    <div class="footer">KiLEX@2012</div>
</div>
</body>
</html>
